package arcsbot.engine

import hrf.colmat._
import arcs._

/* =============================================================================
 * EngineSession — the bridge to the HRF Arcs rules engine.
 *
 * This is an *interactive* version of HRF's `BaseHost.main` (hrf-engine
 * host.scala): the drive loop applies `performContinue` and auto-resolves every
 * `Continue` EXCEPT a real multi-option `Ask`, which it surfaces as a `Turn` for
 * a Discord player instead of handing to the AI bot.
 *
 * The journal is the source of truth: it stores exactly the non-soft external
 * actions (oracle results + committed user choices + the start action), which is
 * what HRF logs. Forced actions are regenerated by the engine on replay; soft
 * Back/Cancel only affect the live session and are never journaled. Seating +
 * options are NOT in the journal (line 0 is just `StartAction(version)`; the
 * campaign start reads `game.seating`/`options` from the Game ctor args), so the
 * session carries them for replay.
 * ===========================================================================*/

/** A faction/seat, by its HRF id ("Red"/"Yellow"/"Blue"/"White"). */
final case class Seat(factionId: String)

/** One legal option in the current decision, already flattened to display text.
  * `index` is the option's position in the engine's current `Ask.actions` list;
  * the bot echoes it back to choose. `kind` distinguishes normal choices from
  * Back/Cancel so the UI can render an "undo step" button. */
final case class MoveOption(index: Int, text: String, kind: MoveOption.Kind)
object MoveOption {
  sealed trait Kind
  case object Choice extends Kind
  case object Back   extends Kind
  case object Cancel extends Kind
  case object Info   extends Kind
}

/** The engine has stopped and needs `seat`'s player to pick one of `options`.
  * `prompt` is the flattened `Ask`/question text. */
final case class Turn(seat: Seat, prompt: String, options: Seq[MoveOption])

/** Result of trying to apply a chosen option, or of driving the engine forward. */
sealed trait Outcome
object Outcome {
  /** Applied; here is the next thing needed (another decision, same or different seat). */
  final case class Next(turn: Turn) extends Outcome
  /** The game ended. */
  final case class GameOver(winners: Seq[Seat]) extends Outcome
  /** The chosen option wasn't legal in the current state (stale UI, race). */
  final case class Rejected(reason: String) extends Outcome
}

/** Owns one Arcs game: its journal, its reconstructed engine state, and its
  * current pending decision. Construct via [[EngineSession.load]] / `create`. */
final class EngineSession private (
    val journal: Journal,
    val factionIds: Seq[String],
    val optionIds: Seq[String]
) {
  import EngineSession._

  private var game: arcs.Game = _
  private var continue: Continue = StartContinue
  private var pendingFaction: Option[Faction] = None
  private var pendingActions: $[UserAction] = $
  private var lastOutcome: Outcome = Outcome.Rejected("uninitialized")

  // Human-readable game log, captured from the engine's `Log` continuations as
  // the drive/replay loops pass through them. Rebuilt from scratch on every
  // replay so it always matches the current (possibly undone) journal.
  private val logBuf = scala.collection.mutable.ArrayBuffer.empty[String]

  // Journal indices of committed player decisions (lines consumed at an
  // `Ask`/`MultiAsk`, i.e. not oracle results and not line 0's StartAction).
  // Maintained incrementally on `apply` and recomputed on every `rebuild`. This
  // is what `undoLast` rolls back; deriving it by parsing journal lines doesn't
  // work because the journal stores `a.unwrap`, which drops the ExternalAction
  // wrapper that distinguishes a choice from an oracle result.
  private val userIdxBuf = scala.collection.mutable.ArrayBuffer.empty[Int]

  // -- public surface --------------------------------------------------------

  /** The current pending state (decision / game-over). Pure: returns the
    * outcome computed by the last create/load/apply/undo. */
  def pending(): Outcome = lastOutcome

  /** The game log so far, one entry per HRF `Log` line (already flattened to
    * plain Discord text), oldest first. Reflects the current journal — entries
    * after an undo point are gone. */
  def log: Seq[String] = logBuf.toVector

  /** True iff there is a committed player decision that `undoLast` could roll
    * back (i.e. at least one decision after the StartAction). */
  def canUndo: Boolean = userIdxBuf.nonEmpty

  /** Undo the most recent committed player decision: truncate the journal back
    * to (and including) that action plus any oracle results it produced, then
    * replay. The player who made it is back on the clock. No-op (returns the
    * current outcome) when there is nothing to undo. HRF etiquette is to gate
    * this behind opponent consent (re-rolls dice/reveals) — deferred; the bot
    * currently only checks the requester holds a seat. */
  def undoLast(): Outcome =
    userIdxBuf.lastOption match {
      case Some(i) => undoTo(i.toLong)
      case None    => lastOutcome
    }

  /** Apply the player's chosen option, validating it against the live decision,
    * then drive forward to the next decision. */
  def apply(seat: Seat, optionIndex: Int): Outcome = {
    pendingFaction match {
      case None => Outcome.Rejected("no decision is pending")
      case Some(f) =>
        if (toSeat(f) != seat)
          Outcome.Rejected(s"not ${seat.factionId}'s turn (waiting on ${f.name})")
        else if (optionIndex < 0 || optionIndex >= pendingActions.num)
          Outcome.Rejected(s"option $optionIndex out of range 0..${pendingActions.num - 1}")
        else {
          val chosen = pendingActions(optionIndex)
          try {
            // Perform first; only journal once the engine accepts the action, so
            // an engine error never leaves a half-written journal line.
            val idx = journal.size
            continue = game.performContinue(|(continue), chosen, false).continue
            // A hard commit becomes a new journal line and an undo point; soft
            // steps (select/Back/Cancel) are live-only and neither.
            if (appendIfHard(chosen)) userIdxBuf += idx.toInt
            advance()
          } catch {
            case e: Throwable =>
              // Restore a consistent state from the (unmodified) journal.
              rebuild()
              Outcome.Rejected("engine could not apply that option: " + msg(e))
          }
        }
    }
  }

  /** Undo to a journal index (truncate + replay). Gate behind opponent consent
    * in the bot (HRF etiquette: ask before undoing dice/reveals). */
  def undoTo(idx: Long): Outcome = {
    journal.truncate(idx)
    rebuild()
  }

  /** Project this game into the strings HRF's browser replay UI consumes — the
    * `#lobby` header (meta/version/title/seating/options in HRF's short-id wire
    * form) and the `#replay` journal lines. The board renderer (Path B) injects
    * these into the host page; nothing arcs.* leaks past this boundary. */
  def replayBundle(title: String = "Arcs Render", at: Int = Int.MaxValue): ReplayBundle =
    EngineSession.buildBundle(journal, factionIds, optionIds, title, at)

  // -- drive loop ------------------------------------------------------------

  /** Drive from the current `continue` through all automatic / oracle / single
    * continuations until the engine stops at a real decision or ends. Oracle
    * steps are resolved with real randomness and their results journaled, so the
    * game stays replayable. */
  private def advance(): Outcome = {
    pendingFaction = None
    pendingActions = $
    var guard = 0
    var result: Outcome = null
    try {
      while (result == null) {
        guard += 1
        if (guard > 1000000) sys.error("drive loop did not terminate")
        liveStep(continue) match {
          case StepOver(winners) =>
            result = Outcome.GameOver(winners.map(toSeat))
          case StepDecide(f, actions) =>
            pendingFaction = Some(f)
            pendingActions = actions
            result = Outcome.Next(toTurn(f, actions))
          case StepApply(a) =>
            continue = game.performContinue(|(continue), a, false).continue
            appendIfHard(a)
        }
      }
    } catch {
      // A continuation this bridge doesn't yet handle (e.g. M5 intermission /
      // hidden-info Fate selection). Surface it instead of crashing the session.
      case e: Throwable =>
        if (sys.env.contains("BRIDGE_DEBUG")) e.printStackTrace()
        result = Outcome.Rejected("engine reached an unsupported continuation: " + msg(e))
    }
    lastOutcome = result
    result
  }

  private def msg(e: Throwable): String =
    Option(e.getMessage).getOrElse(e.getClass.getName).take(200)

  /** Classify the current continuation for LIVE play: oracle steps roll real
    * dice; a single-option Ask auto-applies; only a real multi-option Ask (or
    * MultiAsk) stops for a player. Mirrors host.scala `askFaction`. */
  private def liveStep(c: Continue): Step = c match {
    case ErrorContinue(e, _)            => throw e
    case Force(a)                       => StepApply(a)
    case Then(a)                        => StepApply(a)
    case Milestone(_, a)                => StepApply(a)
    case Log(m, k, cc)                  => captureLog(m, k); liveStep(cc)
    case DelayedContinue(_, cc)         => liveStep(cc)

    case Roll(dice, rolled, _)          => StepApply(rolled(dice./(_.roll())))
    case Roll2(d1, d2, rolled, _)       => StepApply(rolled(d1./(_.roll()), d2./(_.roll())))
    case Roll3(d1, d2, d3, rolled, _)   => StepApply(rolled(d1./(_.roll()), d2./(_.roll()), d3./(_.roll())))
    case Shuffle(l, sh, _)              => StepApply(sh(l.shuffle))
    case Shuffle2(l1, l2, sh, _)        => StepApply(sh(l1.shuffle, l2.shuffle))
    case Shuffle3(l1, l2, l3, sh, _)    => StepApply(sh(l1.shuffle, l2.shuffle, l3.shuffle))
    case ShuffleUntil(l, cond, sh, _)   => StepApply(sh(reshuffleUntil(l, cond)))
    case ShuffleTake(l, n, sh, _)       => StepApply(sh(l.shuffle.take(n)))
    case ShuffleTakeUntil(l, n, c, sh, _) => StepApply(sh(reshuffleTakeUntil(l, n, c)))
    case Random(l, ch, _)               => StepApply(ch(l.shuffle(0)))
    case Random2(l1, l2, ch, _)         => StepApply(ch(l1.shuffle(0), l2.shuffle(0)))
    case Random3(l1, l2, l3, ch, _)     => StepApply(ch(l1.shuffle(0), l2.shuffle(0), l3.shuffle(0)))

    case Ask(f, actions)                => decideAsk(f, actions)
    case MultiAsk(asks, _)              => val a = asks.head; decideAsk(a.faction, a.actions)
    case GameOver(winners, _, _)        => StepOver(winners)
    case StartContinue                  => sys.error("unexpected StartContinue mid-drive")
    case other                          => sys.error("unhandled continuation: " + other)
  }

  /** Turn a raw `Ask` into the decision a player sees.
    *
    * Two shapes of `Ask` reach here:
    *  - **Normal asks** whose actions are high-level "explode" actions; the
    *    engine expands them into concrete performable leaves via `game.explode`
    *    (the same call the bot AI makes — host.scala/bot.scala).
    *  - **Interactive selects** (`YY/XXSelectObjectsAction`, used by Fates and
    *    intermission hidden-info — M5). Their `Ask` is a soft select/deselect/
    *    commit loop fronted by a `HiddenChoice` explode marker. `game.explode`
    *    with `withSoft=false` throws "empty explode" on these because every
    *    meaningful next step is soft, so we instead present the actions directly.
    *
    * Either way we filter exactly as the browser UI does (grey.scala): `Hidden`
    * actions (the `HiddenChoice` explode marker, `HiddenCancelAction`, …) are
    * never shown — exposing one and performing it is what produced the old
    * "unknown continue on …ExplodeAction" crash. Soft select steps are applied
    * one at a time and are not journaled (only the committed hard action is), so
    * replay reconstructs the choice from that single committed line. */
  private def decideAsk(f: Faction, actions: $[UserAction]): Step = {
    // Prefer concrete leaves (the bot's `explode(_, false, None).notOf[Hidden]`).
    // For a valid interactive select this yields the committed-choice leaves; for
    // a degenerate one (nothing valid to pick) it throws "empty explode" and we
    // fall back to the raw actions.
    val expanded = try game.explode(actions, false, None) catch { case _: Throwable => actions }
    val visible  = expanded.filter(_.is[Hidden].not)
    // What a player can actually commit: not Info, not a disabled/unavailable
    // option. (Soft Back/Cancel stay — they're legitimate buttons.)
    val pickable = visible.filter(a => a.is[Info].not && a.is[Unavailable].not)

    if (pickable.nonEmpty) {
      // A lone concrete (non-soft) leaf is forced — auto-apply it. Anything with
      // a real soft step (e.g. a select that re-asks for a commit) goes to the
      // player so we never skip an interaction that still needs a decision.
      if (pickable.num == 1 && pickable.head.isSoft.not) StepApply(pickable.head)
      else StepDecide(f, pickable)
    } else {
      if (sys.env.contains("BRIDGE_DEBUG")) {
        println(s"[decideAsk] no pickable option for $f; raw actions:")
        actions.foreach { a =>
          println(f"  ${a.getClass.getSimpleName}%-32s soft=${a.isSoft} hidden=${a.is[Hidden]} info=${a.is[Info]} unavail=${a.is[Unavailable]} cancel=${a.is[Cancel]} back=${a.is[Back]}  $a")
        }
      }
      // Degenerate select: nothing valid to choose. Surface it so the drive loop
      // doesn't spin (auto-cancel re-issues the same select forever).
      StepDecide(f, visible)
    }
  }

  // -- replay ----------------------------------------------------------------

  /** Rebuild the live game state by replaying the journal. Forced steps are
    * regenerated by the engine; every external/decision point consumes the next
    * journaled action (oracle result, committed choice, or the start action). */
  private def rebuild(): Outcome = {
    game = newGame(factionIds, optionIds)
    continue = StartContinue
    logBuf.clear()      // the replay below re-emits every log line for this journal
    userIdxBuf.clear()  // …and re-derives the undo points
    val lines = journal.lines.iterator
    var lineIdx = 0     // index of the next journal line to consume
    var guard = 0
    var done = false
    while (!done) {
      guard += 1
      if (guard > 2000000) sys.error("replay did not terminate")
      replayStep(continue) match {
        case ReplayForced(a) =>
          continue = game.performContinue(|(continue), a, false).continue
        case ReplayOver =>
          done = true
        case ReplayExternal(decision) =>
          if (!lines.hasNext) done = true            // caught up; live continuation follows
          else {
            if (decision) userIdxBuf += lineIdx      // a committed player choice
            val a = Serialize.parseAction(lines.next())
            continue = game.performContinue(|(continue), a, false).continue
            lineIdx += 1
          }
      }
    }
    advance()
  }

  /** Classify a continuation for REPLAY: forced steps are regenerated; anything
    * that needs an external action (oracle / Ask / MultiAsk) is fed from the
    * journal rather than re-rolled. The first journaled line is the
    * `StartAction`, consumed at the `StartContinue`. */
  private def replayStep(c: Continue): ReplayStep = c match {
    case ErrorContinue(e, _)    => throw e
    case StartContinue          => ReplayExternal(false)     // consume line 0 (StartAction)
    case Force(a)               => ReplayForced(a)
    case Then(a)                => ReplayForced(a)
    case Milestone(_, a)        => ReplayForced(a)
    case Log(m, k, cc)          => captureLog(m, k); replayStep(cc)
    case DelayedContinue(_, cc) => replayStep(cc)
    case GameOver(_, _, _)      => ReplayOver
    case _: Roll[_] | _: Roll2[_, _] | _: Roll3[_, _, _]                  => ReplayExternal(false)
    case _: Shuffle[_] | _: Shuffle2[_, _] | _: Shuffle3[_, _, _]         => ReplayExternal(false)
    case _: ShuffleUntil[_] | _: ShuffleTake[_] | _: ShuffleTakeUntil[_]  => ReplayExternal(false)
    case _: Random[_] | _: Random2[_, _] | _: Random3[_, _, _]            => ReplayExternal(false)
    case _: Ask | _: MultiAsk   => ReplayExternal(true)      // a committed player decision
    case other                  => sys.error("unhandled continuation in replay: " + other)
  }

  // -- helpers ---------------------------------------------------------------

  /** Journal `a` iff it's a hard ExternalAction. Returns true when a line was
    * actually written (the caller uses this to mark undo points). */
  private def appendIfHard(a: Action): Boolean =
    if (a.is[ExternalAction] && a.isSoft.not) {
      val line = Serialize.write(a.unwrap)
      journal.append(journal.size, line) match {
        case Right(_)        => true
        case Left(conflict)  => sys.error(s"journal append conflict: $conflict")
      }
    } else false

  private def toTurn(f: Faction, actions: $[UserAction]): Turn = {
    implicit val g: arcs.Game = game
    val prompt  = actions.headOption.map(a => safeText(a.question, "")).getOrElse("")
    val options = 0.until(actions.num).map { i =>
      val a = actions(i)
      MoveOption(i, safeText(a.option, a.toString), kindOf(a))
    }
    Turn(toSeat(f), prompt, options)
  }

  /** Render an Elem to text, falling back when it throws. `Hidden` actions
    * (private-info choices) throw on `question`/`option` by design
    * (base.scala Hidden); their owning player still needs a label, so we fall
    * back to the action's structural string. */
  private def safeText(e: => hrf.elem.Elem, fallback: => String): String =
    try ElemText.render(e) catch { case _: Throwable => fallback }

  /** Record a `Log` continuation's message in the game log. Only `Normal` lines
    * are kept; `Temp` ones are transient UI hints. Empty/whitespace renders are
    * dropped so the log stays readable. */
  private def captureLog(message: hrf.elem.Elem, kind: LogKind): Unit =
    if (kind == LogKind.Normal) {
      val t = ElemText.render(message)
      if (t.nonEmpty) logBuf += t
    }

  private def kindOf(a: UserAction): MoveOption.Kind =
    if (a.is[Back]) MoveOption.Back
    else if (a.is[Cancel]) MoveOption.Cancel
    else if (a.is[Info]) MoveOption.Info
    else MoveOption.Choice

  private def reshuffleUntil[T](l: $[T], cond: $[T] => Boolean): $[T] = {
    var r = l.shuffle; while (!cond(r)) r = l.shuffle; r
  }
  private def reshuffleTakeUntil[T](l: $[T], n: Int, cond: $[T] => Boolean): $[T] = {
    var r = l.shuffle.take(n); while (!cond(r)) r = l.shuffle.take(n); r
  }
}

object EngineSession {

  private def toSeat(f: Faction): Seat = Seat(f.name)

  private val factionByName: Map[String, Faction] =
    Map("Red" -> Red, "White" -> White, "Blue" -> Blue, "Yellow" -> Yellow)

  /** The campaign options a `create` caller may name. Includes a campaign-mode
    * option (required for a Blighted Reach game: `game.campaign` is true iff the
    * options contain a CampaignOption). */
  private val optionByName: Map[String, hrf.meta.GameOption] = Map(
    "HostTest"                 -> HostTest,
    "RandomPlayerOrder"        -> RandomPlayerOrder,
    "RandomizePlanetResources" -> RandomizePlanetResources,
    "RandomizeStartingSystems" -> RandomizeStartingSystems,
    "LeadersAndLore"           -> LeadersAndLore,
    "DoubleLore"               -> DoubleLore,
    "TripleLore"               -> TripleLore,
    "NoFate"                   -> NoFate,
    "Act1Only"                 -> Act1Only,
    "SetupActTwo"              -> SetupActTwo
  )

  /** Sensible default for a valid full Blighted Reach campaign (Acts I–III).
    * `NoFate` is the campaign-mode option the dev build (MetaBR.development, our
    * `test-` version) defaults to; it lifts the public build's mandatory
    * `Act1Only` gate. `Act1Only` is not listed in `MetaBR.options` under dev mode,
    * so using it here would desync the renderer's lobby from the browser. */
  val DefaultOptionIds: Seq[String] = Seq("NoFate", "RandomPlayerOrder", "RandomizePlanetResources")

  private def parseFaction(id: String): Faction =
    factionByName.getOrElse(id, sys.error(s"unknown faction '$id' (expected Red/White/Blue/Yellow)"))

  private def parseOption(id: String): hrf.meta.GameOption =
    optionByName.getOrElse(id, sys.error(s"unknown option '$id' (known: ${optionByName.keys.toSeq.sorted.mkString(", ")})"))

  private def newGame(factionIds: Seq[String], optionIds: Seq[String]): arcs.Game = {
    val setup   = factionIds.map(parseFaction).toList
    val options = optionIds.map(parseOption).toList
    new arcs.Game(setup, options)
  }

  /** Load (or resume) a game by replaying its journal through the HRF engine.
    * Seating + options must be supplied (they live outside the journal). */
  def load(journal: Journal, factionIds: Seq[String], optionIds: Seq[String]): EngineSession = {
    require(journal.size > 0, "cannot load an empty journal — use create")
    val s = new EngineSession(journal, factionIds, optionIds)
    s.lastOutcome = s.rebuild()
    s
  }

  /** Create a brand-new Arcs: The Blighted Reach game: validate the seating,
    * build the `arcs.Game`, write `StartAction` as journal line 0, and drive to
    * the first decision. */
  def create(journal: Journal, factionIds: Seq[String], optionIds: Seq[String] = DefaultOptionIds): EngineSession = {
    require(journal.size == 0, "cannot create on a non-empty journal — use load")
    val setup   = factionIds.map(parseFaction).toList
    val options = optionIds.map(parseOption).toList
    val validation = MetaBR.validateFactionSeatingOptions(setup, options)
    if (!validation.ok) sys.error("invalid setup: " + validation.message)

    val s = new EngineSession(journal, factionIds, optionIds)
    s.game = new arcs.Game(setup, options)
    val start = StartAction(version)
    journal.append(0, Serialize.write(start)) match {
      case Right(_)       => ()
      case Left(conflict) => sys.error(s"journal append conflict on start: $conflict")
    }
    s.continue = s.game.performContinue(|(StartContinue), start, false).continue
    s.lastOutcome = s.advance()
    s
  }

  /** Build the HRF browser-replay projection from a journal + seating/options.
    * `seating`/`options` are emitted in HRF's short-id wire form (what the
    * browser's `readLobby` / `parseFaction` / `parseOption` expect); the replay
    * lines are the journal verbatim — `MetaBR.writeActionExternal` is exactly
    * `Serialize.write(a.unwrap)`, which is what the journal already stores. */
  private[engine] def buildBundle(
      journal: Journal, factionIds: Seq[String], optionIds: Seq[String],
      title: String, at: Int): ReplayBundle = {
    val seating = factionIds.map(id => MetaBR.writeFaction(parseFaction(id)))
    val options = optionIds.map(id => MetaBR.writeOption(parseOption(id)))
    val lobby = Seq(
      "meta arcs-br",
      "version " + version,
      "title " + title,
      "seating " + seating.mkString(" "),
      "options " + options.mkString(" ")
    )
    val replay = journal.lines
    ReplayBundle(lobby, replay, math.min(at, replay.length))
  }

  // internal step ADTs (top-level in the companion so the type tests have no
  // unstable outer reference; arcs.* types are package-object members).
  private sealed trait Step
  private final case class StepApply(a: arcs.Action) extends Step
  private final case class StepDecide(f: arcs.Faction, actions: List[arcs.UserAction]) extends Step
  private final case class StepOver(winners: List[arcs.Faction]) extends Step

  private sealed trait ReplayStep
  private final case class ReplayForced(a: arcs.Action) extends ReplayStep
  /** Consume the next journal line. `decision` = it's a committed player choice
    * (an `Ask`/`MultiAsk`), so its index is an undo point. */
  private final case class ReplayExternal(decision: Boolean) extends ReplayStep
  private case object ReplayOver extends ReplayStep
}
